---
title: "A_GTP_exploring_phenotype_data"
output:
  html_notebook:
    toc: yes
    toc_float: yes
date: "Jan. 21, 2020"
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
.libPaths( c( "/opt/R/3.6.2/lib/R/library" , .libPaths() ) )
```

```{r}
library(tidyverse)
library(readxl)
```


## load datasets

```{r}
# phenotype data
GTP_pheno1 <- read_delim("/data/humgen/GTP_genomics/PLINK/input/pheno/gtp_screen_pheno.txt",
                         col_names = TRUE, delim = "\t")
GTP_pheno2 <- read_delim("/data/humgen/GTP_genomics/PLINK/input/pheno/Masterdataset_2-2-15_cleaned_reduced_For_Machine_Learning_5-25-2016.txt",
                         col_names = TRUE, delim = "\t")
```

```{r}
GTP_pheno3 <- read_excel("/data/humgen/GTP_genomics/PLINK/input/pheno/ResslerData_cleaned_reduced_For Machine Learning_withSIDs.xlsx", sheet = 1) %>% 
  print() 

GTP_pheno3 %>% 
#  count(sex)
#  count(PTSD_diagnosis)
  subset(select=c("sex","PTSD_diagnosis")) %>% table()

```

Now let's focus on samples with genotype data.
```{r}
# GTP pheno data
t1 <- read_delim("/data/humgen/burook/GTP_analysis/table_pred", col_names = TRUE, delim = " ") 
gtp_pheno1 <- read_delim("/data/humgen/burook/GTP_analysis/GTP_pheno1.txt", col_names = TRUE, delim = "\t") %>% 
  inner_join(t1, by=c("IID"="Sample")) 
```

```{r}
# install necessary packages
#install.packages("arsenal",  method = "curl", lib = "/PHShome/bm363/R/x86_64-pc-linux-gnu-library/3.6")
#install.packages("Amisc",  method = "curl", lib = "/PHShome/bm363/R/x86_64-pc-linux-gnu-library/3.6")
#install.packages("table1",  method = "curl", lib = "/PHShome/bm363/R/x86_64-pc-linux-gnu-library/3.6")

# clean up data for demo table
tab_data1 <- gtp_pheno1 %>% 
  mutate(PTSD_diagnosis = na_if(na_if(PTSD_diagnosis,"2092"),"7011")) %>% 
  mutate(PTSD_diagnosis = factor(PTSD_diagnosis, labels = c("Controls","Cases"))) %>% 
  filter(!is.na(PTSD_diagnosis))

# we can use this package if we need significance tests conducted
library(arsenal)

sum_tab1 <- tableby(PTSD_diagnosis ~ PSStotal + BDItotalscore + as.factor(BDI_CAT) + age + as.factor(sex) + education + CTQTOT + as.factor(race_ethnic), data=tab_data1, test=T)
summary(sum_tab1)


# a better lookong descriptive tables can be generated with the following package
library(table1)
label(tab_data1$PTSD_diagnosis) <- "PTSD Diagnosis"
label(tab_data1$age) <- "Age"
label(tab_data1$sex) <- "Sex"
label(tab_data1$race_ethnic) <- "Race/Ethnicity"
label(tab_data1$CTQTOT) <- "Childhood trauma score"

sum_tab2 <- table1(~ PSStotal + BDItotalscore + age + as.factor(sex) + education + CTQTOT + as.factor(race_ethnic) | PTSD_diagnosis, 
                   data = tab_data1)#, overall = FALSE)
sum_tab2
```

- What is a better trauma exposure measure we should use?
- Do we have CRP and other molecular markers measured?
- Do we have BMI and other anthropometric measurements?



```{r}
gtp_pheno2 <- gtp_pheno1 %>% 
#  filter(!is.na(PTSD_status)) %>% 
#  filter(PTSD_status<125) %>% 
  subset(select=c("PTSD_diagnosis", "CTQTOT","education")) %>% 
  mutate(CA4 = cut(CTQTOT, breaks = c(-Inf,40,60,80,Inf), right=T,labels = F)) %>%
  mutate(EA4 = cut(education, breaks = c(-Inf,1,3,4,Inf), right=T,labels = F)) 

gtp_pheno2 %>% print()
#, labels=c("low","midlow","midhigh","high")

```

```{r}
x=table(gtp_pheno2[,c("PTSD_diagnosis","EA4")])
y <- x[c(2,1),]
barplot(y)

#par(mfrow=c(1, 1), mar=c(5, 5, 5, 10), xpd=TRUE)
barplot(prop.table(y, margin = 2), beside=F, horiz=F,
        col=c("red","steelblue"),
        legend = rownames(y), legend.text = TRUE,
        args.legend = list(x = "topright", bty = "n", inset=c(-0.25,0)),
        cex.lab=1.5,
        main = "Conditional probability of PTSD diagnosis",
        ylab = "Proportion with PTSD",
        xlab = "Education level")#,
        #names.arg = c("H.S. Diploma \n or less","A.A. Degree \n(2 yrs)","Bachelor's \n Degree (4 yrs)","Master's \n Degree or more"))

```

```{r}
x=table(gtp_pheno2[,c("PTSD_diagnosis","CA4")])
y <- x[c(2,1),]
barplot(y)

#par(mfrow=c(1, 1), mar=c(5, 5, 5, 10), xpd=TRUE)
barplot(prop.table(y, margin = 2), beside=F, horiz=F,
        col=c("red","steelblue"),
        legend = rownames(y), legend.text = TRUE,
        args.legend = list(x = "topright", bty = "n", inset=c(-0.25,0)),
        cex.lab=1.5,
        main = "Conditional probability of PTSD diagnosis",
        ylab = "Proportion with PTSD",
        xlab = "Childhood Adversity")

```

