---
title: "D_PRS_computation_and_analysis"
output:
  html_notebook:
    toc: yes
    toc_float: yes
date: "May 5, 2020"
---


```{r}
.libPaths( c( "/opt/R/3.6.2/lib/R/library" , .libPaths() ) )
.libPaths()
```

```{r}
library(tidyverse)
library(readxl)
```


# Computing PRS with  PRSice

## PTSD-PRS

Prepare PTSD pheno file for PRSice


Let's prepare the pheno file for PRScise
```{r}
# all samples
pheno_file_PTSD_status2 <- read_delim("/data/humgen/burook/GTP_analysis/GTP_pheno1.txt", col_names = TRUE, delim = "\t") %>% 
  subset(select=c("IID","PTSD_diagnosis")) %>%  
  filter(PTSD_diagnosis==0 | PTSD_diagnosis==1) 

write.table(pheno_file_PTSD_status2, "/data/humgen/burook/GTP_analysis/gtp_ptsd/pheno_file_PTSD_status2", row.names = FALSE, col.names = FALSE, quote = FALSE)

t1 <- read_delim("/data/humgen/burook/GTP_analysis/table_pred", col_names = TRUE, delim = " ") 

# AFR ancestry samples
pheno_file_PTSD_status2_afr <- pheno_file_PTSD_status2 %>% 
  inner_join(t1, by=c("IID"="Sample")) %>% 
  filter(predtree=='AFR') %>%
  subset(select=c("IID","PTSD_diagnosis")) %>% 
  print()

write.table(pheno_file_PTSD_status2_afr, "/data/humgen/burook/GTP_analysis/gtp_ptsd_afr/pheno_file_PTSD_status2_afr", row.names = FALSE, col.names = FALSE, quote = FALSE)

# non-AFR ancestry samples
pheno_file_PTSD_status2_nonafr <- pheno_file_PTSD_status2 %>% 
  inner_join(t1, by=c("IID"="Sample")) %>% 
  filter(predtree!='AFR') %>%
  subset(select=c("IID","PTSD_diagnosis")) %>% 
  print()

write.table(pheno_file_PTSD_status2_nonafr, "/data/humgen/burook/GTP_analysis/gtp_ptsd_nonafr/pheno_file_PTSD_status2_nonafr", row.names = FALSE, col.names = FALSE, quote = FALSE)

```


```{bash}
cd /data/humgen/burook/GTP_analysis/gtp_ptsd/

/PHShome/bm363/bin/plink2 \
  --bfile /data/humgen/GTP_genomics/PLINK/input/PGC_GTP_June2017/GTPC/qc/pts_gtpc_mix_am-qc \
  --maf 0.01 \
  --geno 0.01 \
  --mind 0.1 \
  --hwe 0.001 \
  --make-bed \
  --out tmp_gtp1

```


```{bash}
# with freeze-2 PGC-PTSD summ stats
R --file=/PHShome/bm363/bin/PRSice_v1.25/PRSice_v1.25.R -q --args  \
  plink /PHShome/bm363/bin/plink2 \
  base /data/humgen/burook/sum_stats/pts_eur_freeze2_overall.results \
  target /data/humgen/burook/GTP_analysis/gtp_ptsd/tmp_gtp1 \
  pheno.file /data/humgen/burook/GTP_analysis/gtp_ptsd/pheno_file_PTSD_status2 \
  binary.target T \
  covariates C1,C2,C3,C4,C5,C6,C7,C8,C9,C10 \
  figname gtp_ptsd \
  wd /data/humgen/burook/GTP_analysis/gtp_ptsd/
```



## Analysis of the constructed PRS

```{r}
# let's load necessary files for performance analysis and plots
gtp_pheno1 <- read_delim("/data/humgen/burook/GTP_analysis/GTP_pheno1.txt", col_names = TRUE, delim = "\t") 
pcs1 = read.table("/data/humgen/burook/GTP_analysis/gtp_ptsd/ANCESTRY_INFORMATIVE_DIMENSIONS.mds", header = TRUE) 
prs1 = read.table("/data/humgen/burook/GTP_analysis/gtp_ptsd/gtp_ptsd_SCORES_AT_BEST-FIT-PRS.txt", header = TRUE) 
prs1[,2]=scale(prs1[,2],center=T,scale=T); colnames(prs1)=c("IID","prs");

# also let's load the file containing predicted ancestry labels
t1 <- read_delim("/data/humgen/burook/GTP_analysis/table_pred", col_names = TRUE, delim = " ") 

gtp_pheno1 <- read_delim("/data/humgen/burook/GTP_analysis/GTP_pheno1.txt", col_names = TRUE, delim = "\t") %>% 
  inner_join(t1, by=c("IID"="Sample")) 



PTSD_all_data <- t1 %>% 
  filter(is.na(SuperPopulation)) %>% 
  mutate(IID=as.character(Sample)) %>% 
  full_join(gtp_pheno1, by=c("IID")) %>%
  full_join(pcs1, by=("IID")) %>% 
  full_join(prs1, by=("IID")) %>% 
  filter(PTSD_diagnosis==0 | PTSD_diagnosis==1) %>% 
  mutate(PTSD_diagnosis = factor(PTSD_diagnosis, labels =c(0,1))) %>% 
  filter(!is.na(prs))
#  filter(predtree=='AFR') %>% 

```

```{r}
require(fmsb) # for NagelkerkeR2 calculation

predictors1 <- c("prs")
covariates <- c("C1","C2","C3","C4","C5","C6","C7","C8","C9","C10")  # c(,"DemoAge","DemoGend")

model.full <- glm(as.factor(PTSD_diagnosis) ~., family="binomial", data = PTSD_all_data[,c("PTSD_diagnosis", predictors1, covariates)])
model.null <-  glm(as.factor(PTSD_diagnosis) ~., family="binomial", data = PTSD_all_data[,c("PTSD_diagnosis",covariates)])

paste("R^2 = ", 
100*(NagelkerkeR2(model.full)$R2 - NagelkerkeR2(model.null)$R2),  # Nagelkerke R^2
", P = ",
summary(model.full)$coefficients[2,4]  ) # p-value only when there is only one predictor variable

```

```{r}
source('/data/humgen/burook/ptsd_multimodal_prediction_stage1/R/quantile_plot_and_stats.R')
#pdf("//.../quantiles_oddsRatio_ptsd_prs1.pdf", width=5.5, height=5)
plot1=quantile_plot_and_stats(prs = prs1, 
                              pcs = pcs1, 
                              pheno.data.all = PTSD_all_data, 
                              covariates = c("C1","C2","C3","C4","C5"),
                              num.quantiles = 4, binary.pheno = T, pheno.name = "PTSD_diagnosis")
#                              num.quantiles = 4, binary.pheno = F, pheno.name = "CAPSTOT_cur")

plot1

#dev.off()
#plot1
```



Distribution of the PTSD-PRS 
```{r}
plot1 <- PTSD_all_data %>% 
  filter(!is.na(prs)) %>% 
ggplot(aes(x=prs)) + 
  geom_histogram(aes(y =..density..), 
                 col="darkgreen", 
                 fill="navyblue", 
                 alpha=.2, binwidth=0.1) +
  ylab("Count") + 
  xlab("PTSD-PRS") +
  geom_density(col="red")

plot1

```


