---
title: "E_Testing_the_trivariate_model_on_GTP"
output:
  html_notebook:
    toc: yes
    toc_float: yes
date: "May 5, 2020"
---


```{r}
.libPaths( c( "/opt/R/3.6.2/lib/R/library" , .libPaths() ) )
.libPaths()
```

```{r}
library(tidyverse)
```


## Load data

```{r}
pcs1 = read.table("/data/humgen/burook/GTP_analysis/gtp_ptsd/ANCESTRY_INFORMATIVE_DIMENSIONS.mds", header = TRUE) 
prs1 = read.table("/data/humgen/burook/GTP_analysis/gtp_ptsd/gtp_ptsd_SCORES_AT_BEST-FIT-PRS.txt", header = TRUE) 
prs1[,2]=scale(prs1[,2],center=T,scale=T); colnames(prs1)=c("IID","prs");

gtp_pheno2 <- read_delim("/data/humgen/burook/GTP_analysis/GTP_pheno1.txt", col_names = TRUE, delim = "\t") %>% 
#  filter(!is.na(PTSD_status)) %>% 
#  filter(PTSD_status<125) %>% 
  full_join(pcs1, by=("IID")) %>% 
  full_join(prs1, by=("IID")) %>% 
  filter(PTSD_diagnosis==0 | PTSD_diagnosis==1) %>% 
  mutate(PTSD_status = factor(PTSD_diagnosis, labels =c("Negative","Positive"))) %>% 
  mutate(CA4 = cut(CTQTOT, breaks = c(-Inf,40,60,80,Inf), right=T,labels = F)) %>%
  mutate(EA4 = cut(education, breaks = c(-Inf,1,3,4,Inf), right=T,labels = F)) %>% 
  subset(select=c("PTSD_status","PSStotal", "CTQTOT","education","CA4","EA4","prs")) %>% 
  filter(!is.na(prs))

```


```{r}
load(file = "/data/humgen/burook/ptsd_multimodal_prediction_stage1/model1.RData")

Test1 <- gtp_pheno2 %>% 
  filter(complete.cases(gtp_pheno2[,c("PTSD_status", "prs", "CA4", "EA4")])) %>% 
  subset(select=c("PTSD_status", "prs", "CA4", "EA4")) 

xTest1 <- as.matrix(Test1[,c("prs","CA4","EA4")])
yTest1 <- factor(as_vector(Test1[,c("PTSD_status")]), labels = c("control","case"))


require(pROC)

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# logistic regression
require(caret)
pred = predict(lr1, newdata=as.data.frame(xTest1), type='prob')
AUC3[1,2] = (pROC::roc(yTest1, pred[,1],ci=F))$auc

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SVM
require(kernlab)   
pred = predict(svm1, newdata=xTest1, type="prob")
AUC3[2,2] = (pROC::roc(as.factor(yTest1), pred[,1],ci=T))$auc

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# boosted tree
require(gbm)   
pred = predict(svm1, newdata=xTest1, type="prob")
AUC3[3,2] = (pROC::roc(as.factor(yTest1), pred[,1],ci=T))$auc

###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Random forest
require(randomForest)
pred = predict(rf1, newdata=xTest1, type="prob")
AUC3[4,2] = (pROC::roc(as.factor(yTest1), pred[,1],ci=T))$auc
AUC3

```


