---
title: "E_Testing_the_trivariate_model_on_GTP"
output:
  html_notebook:
    toc: yes
    toc_float: yes
date: "May 5, 2020"
---


```{r}
.libPaths( c( "/opt/R/3.6.2/lib/R/library" , .libPaths() ) )
```

```{r}
library(tidyverse)
```


## Load data

```{r}
# Ft. Campbell pheno data
pcs1 = read.table("/data/humgen/burook/FC_analysis/fc_ptsd/ANCESTRY_INFORMATIVE_DIMENSIONS.mds", header = TRUE) %>% 
  mutate(IID = as.character(as.numeric(str_sub(IID,start=6)))) 
prs1 = read.table("/data/humgen/burook/FC_analysis/fc_ptsd/fc_ptsd_SCORES_AT_BEST-FIT-PRS.txt", header = TRUE) %>% 
  mutate(IID = as.character(as.numeric(str_sub(IID,start=6))))
prs1[,2]=scale(prs1[,2],center=T,scale=T); colnames(prs1)=c("IID","prs");
t1 <- read_delim("/data/humgen/burook/FC_analysis/table_pred", col_names = TRUE, delim = " ") 


fc_pheno2 <- read_delim("/data/humgen/burook/data_raw/fc/clinical/FC_data_for_PGM.txt", col_names = TRUE, delim = "\t") %>%
  # prs with freeze1 is already in this data frame. Let's normalize and rename it.
  mutate(prs = scale(prs,center=T,scale=T)) %>% 
  dplyr::rename(prs_freeze1=prs) %>% 
  mutate(IID=as.character(ID)) %>% 
  full_join(t1, by=c("IID"="Sample")) %>% 
  filter(is.na(SuperPopulation)) %>% 
  full_join(pcs1, by=("IID")) %>% 
  full_join(prs1, by=("IID")) %>%  
  filter(PTSD_status=="Negative" | PTSD_status=="Positive") %>% 
  filter(predtree=='AFR') %>% 
  mutate(PTSD_status = factor(PTSD_status, labels =c("Negative","Positive"))) %>%
  mutate(CA4 = cut(CTQ_total_abuse_score, breaks = c(-Inf,20,30,40,Inf), right=T, labels = F)) %>% 
  mutate(EA4 = cut(EDUCATION_LEVEL, breaks = c(-Inf,2,3,4,Inf), right=T, labels = F)) %>% 
  mutate(prs_quantiles = cut(prs, breaks = quantile(prs1$prs, probs = seq(0, 1, 1/4)), include.lowest=T)) %>% 
  mutate(prs_quantiles=as.numeric(prs_quantiles)) %>% 
  subset(select=c("PTSD_status","PCL_score","CTQ_total_abuse_score","EDUCATION_LEVEL","CA4","EA4","prs","prs_quantiles", "prs_freeze1","C1","C2","C3","C4","C5","IID")) 
  
```



```{r}
# GTP pheno data
pcs1 = read.table("/data/humgen/burook/GTP_analysis/gtp_ptsd/ANCESTRY_INFORMATIVE_DIMENSIONS.mds", header = TRUE) 
prs1 = read.table("/data/humgen/burook/GTP_analysis/gtp_ptsd/gtp_ptsd_SCORES_AT_BEST-FIT-PRS.txt", header = TRUE) 
prs1[,2]=scale(prs1[,2],center=T,scale=T); colnames(prs1)=c("IID","prs");
t1 <- read_delim("/data/humgen/burook/GTP_analysis/table_pred", col_names = TRUE, delim = " ")

gtp_pheno2 <- read_delim("/data/humgen/burook/GTP_analysis/GTP_pheno1.txt", col_names = TRUE, delim = "\t") %>% 
#  filter(!is.na(PTSD_status)) %>% 
  full_join(t1, by=c("IID"="Sample")) %>% 
  filter(is.na(SuperPopulation)) %>% 
  full_join(pcs1, by=("IID")) %>% 
  full_join(prs1, by=("IID")) %>% 
  filter(PTSD_diagnosis==0 | PTSD_diagnosis==1) %>% 
  filter(predtree=='AFR') %>% 
  mutate(PTSD_status = factor(PTSD_diagnosis, labels =c("Negative","Positive"))) %>% 
  mutate(CA4 = cut(CTQTOT, breaks = c(-Inf,40,60,80,Inf), right=T,labels = F)) %>%
  mutate(EA4 = cut(education, breaks = c(-Inf,1,3,4,Inf), right=T,labels = F)) %>% 
  mutate(prs_quantiles = cut(prs, breaks = quantile(prs1$prs, probs = seq(0, 1, 1/4)), include.lowest=T)) %>% 
  mutate(prs_quantiles=as.numeric(prs_quantiles)) %>% 
  subset(select=c("PTSD_status","PSStotal", "CTQTOT","education","CA4","EA4","prs","prs_quantiles","C1","C2","C3","C4","C5","IID")) 

```


```{r}
# AURORA pheno data
# let's load necessary files for performance analysis and plots
aur_pheno1 <- read_delim("/data/humgen/burook/AURORA/aur_pheno1.txt", col_names = TRUE, delim = "\t")
pcs1 = read.table("/data/humgen/burook/AURORA/aur_ptsd_afr/ANCESTRY_INFORMATIVE_DIMENSIONS.mds", header = TRUE)
prs1 = read.table("/data/humgen/burook/AURORA/aur_ptsd_afr/aur_ptsd_SCORES_AT_BEST-FIT-PRS.txt", header = TRUE)
prs1[,2]=scale(prs1[,2],center=T,scale=T); colnames(prs1)=c("IID","prs");
prs1[,2] = -1*prs1[,2]      # the prs sign is inverted, let's correct it
# also let's load the file containing predicted ancestry labels
t1 <- read_delim("/data/humgen/burook/AURORA/table_pred", col_names = TRUE, delim = " ")

aur_pheno2 <- t1 %>% 
  filter(is.na(SuperPopulation)) %>% 
  mutate(IID=Sample) %>% 
  full_join(aur_pheno1, by="IID") %>% 
  full_join(pcs1, by="IID") %>% 
  full_join(prs1, by="IID") %>% 
  filter(!is.na(prs)) %>% 
  filter(predtree=='AFR') %>% 
  mutate(PTSD_status = factor(M3_PCL5, labels =c("Negative","Positive"))) %>% 
  mutate(CA4 = as.numeric(cut(WK2_CTQSF_Total_RS, breaks = c(-Inf,1,4,7,9), right=T))) %>% 
  mutate(EA4 = cut(ED_HighestGrade, breaks = c(-Inf,12,14,16,17), right=T,labels = F)) %>% 
  mutate(prs_quantiles = cut(prs, breaks = quantile(prs1$prs, probs = seq(0, 1, 1/4)), include.lowest=T)) %>% 
  mutate(prs_quantiles=as.numeric(prs_quantiles)) %>% 
  subset(select=c("PTSD_status","M3_PCL5_RS", "WK2_CTQSF_Total_RS","ED_HighestGrade","CA4","EA4","prs","prs_quantiles","C1","C2","C3","C4","C5","IID"))

```


```{r}
load(file = "/data/humgen/burook/ptsd_multimodal_prediction_stage1/model1.RData")


require(pROC)

for (j in (2:4)) {
  if (j==2){         # FC
    Test1 <- fc_pheno2 %>% 
      filter(complete.cases(fc_pheno2[,c("PTSD_status", "prs", "CA4", "EA4")])) %>% 
      subset(select=c("PTSD_status", "prs_quantiles", "CA4", "EA4")) 
    xTest1 <- as.matrix(Test1[,c("prs_quantiles","CA4","EA4")])
    yTest1 <- factor(as_vector(Test1[,c("PTSD_status")]), labels = c("control","case"))
  }
  if (j==3){         # GTP
    Test1 <- gtp_pheno2 %>% 
      filter(complete.cases(gtp_pheno2[,c("PTSD_status", "prs", "CA4", "EA4")])) %>% 
      subset(select=c("PTSD_status", "prs_quantiles", "CA4", "EA4")) 
    xTest1 <- as.matrix(Test1[,c("prs_quantiles","CA4","EA4")])
    yTest1 <- factor(as_vector(Test1[,c("PTSD_status")]), labels = c("control","case"))
  }
  if (j==4){         # AURORA
    Test1 <- aur_pheno2 %>% 
      filter(complete.cases(aur_pheno2[,c("PTSD_status", "prs", "CA4", "EA4")])) %>% 
      subset(select=c("PTSD_status", "prs_quantiles", "CA4", "EA4")) 
    xTest1 <- as.matrix(Test1[,c("prs_quantiles","CA4","EA4")])
    yTest1 <- factor(as_vector(Test1[,c("PTSD_status")]), labels = c("control","case"))
  }

  
  for (i in (1:4)) {
    ###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# logistic regression
    if (i==1){          
      require(caret)
      pred = predict(lr1, newdata=as.data.frame(xTest1), type='prob')
      AUC3[i,j] = (pROC::roc(yTest1, pred[,1],ci=F))$auc
    }
    ###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# SVM
    if (i==2){          
      require(kernlab)   
      pred = predict(svm1, newdata=xTest1, type="prob")
      AUC3[i,j] = (pROC::roc(as.factor(yTest1), pred[,1],ci=T))$auc
    }
    ###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# boosted tree
    if (i==3){          
      require(gbm)   
      pred = predict(gbm1, newdata=xTest1, type="prob")
      AUC3[i,j] = (pROC::roc(as.factor(yTest1), pred[,1],ci=T))$auc
    }
    ###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# Random forest
    if (i==4){          
      require(randomForest)
      pred = predict(rf1, newdata=xTest1, type="prob")
      AUC3[i,j] = (pROC::roc(as.factor(yTest1), pred[,1],ci=T))$auc
    }
  }
}



AUC3

```


A function to compute performace parameters
```{r}
calc_R2 <- function(Data_all=fc_pheno2, predictors1="case", response1="PCL_score", response2="PTSD_status", covariates = c("C1","C2","C3","C4","C5"))
{
  require(pROC) # AUC computation
  require(survival) # for C-index computation
  require(caret)
  
  r2.out <- matrix(rep(0,7),nrow = 1)
  names(r2.out) <- c("R2", "NagelkerkeR2", "P1", "P2","C-index","OR","delta")
  
  # compute logistic regression predictions
  Test1 <- Data_all %>% 
  filter(complete.cases(Data_all[,c("PTSD_status", "prs", "CA4", "EA4")])) %>% 
  subset(select=c("PTSD_status", response1,"prs_quantiles", "CA4", "EA4","C1","C2","C3","C4","C5","IID")) 
  xTest1 <- as.matrix(Test1[,c("prs_quantiles","CA4","EA4")])
  yTest1 <- factor(as_vector(Test1[,c("PTSD_status")]), labels = c("control","case"))
  pred <- predict(lr1, newdata=as.data.frame(xTest1), type='prob')
  Test2 <- cbind(Test1,pred)
  
  ####---------------------
  # Odds-ratio between quantiles
  source('/data/humgen/burook/ptsd_multimodal_prediction_stage1/R/quantile_plot_and_stats.R')
  
  plot1=quantile_plot_and_stats(prs = Test2[c("IID","case")], 
                              pcs = Test2[c("IID","C1","C2","C3","C4","C5")], 
                              pheno.data.all = Test1, 
                              covariates = c("C1","C2","C3","C4","C5"),
                              num.quantiles = 4, binary.pheno = T, pheno.name = "PTSD_status")
  #                              num.quantiles = 4, binary.pheno = F, pheno.name = "CAPSTOT_cur")
  r2.out["OR"] <- plot1[["OR"]][4]
  
  ####---------------------
  y1 <- Test2[,response1]
  
  # R2
  model.full <- glm(as.formula(paste(response1,"~ .")), family="gaussian", data = Test2[,c(response1, predictors1, covariates)])
  model.null <-  glm(as.formula(paste(response1,"~ .")), family="gaussian", data = Test2[,c(response1, covariates)])


  r2.out["R2"] <-   (1 - sum( (y1-predict(model.full))^2 ) / sum( (y1-mean(y1))^2 )  ) - (1 - sum( (y1-predict(model.null))^2 ) / sum( (y1-mean(y1))^2 )  )
  #r2.out[3] <- summary(model.full)$coefficients[2,4]  # p-value only when there is only one predictor variable
  
  ####---------------------
  require(fmsb) # for NagelkerkeR2 calculation
  model.full <- glm(as.formula(paste(response2,"~ .")), family="binomial", data = Test2[,c(response2, predictors1, covariates)])
  model.null <-  glm(as.formula(paste(response2,"~ .")), family="binomial", data = Test2[,c(response2, covariates)])
  
  r2.out["NagelkerkeR2"] <- NagelkerkeR2(model.full)$R2 - NagelkerkeR2(model.null)$R2
  #r2.out[4] <- summary(model.full)$coefficients[2,4]  # p-value only when there is only one predictor variable
  
  ####---------------------
  # C-index computations
  r2.out["C-index"] <- summary(coxph(Surv(as.numeric(Test2$case))~y1))$concordance["C"]
  
  
  # convert to percentage
#  r2.out[1:2] <- 100*(r2.out[1:2])
  return(r2.out)
}

```


```{r}
# a matrix to hold the performances of the models
perf1 <- matrix(0, nrow = 6, ncol = 4)
rownames(perf1) <- c("AUC", "NagelkerkeR2", "OR", "C-index", "R2","delta")
colnames(perf1) <- c("SysBio","FC","GTP","AURORA")

# AUC's are already computed
perf1["AUC",] <- AUC3["logistic regression",]


######## R^2 and C-index computations as well as odds-ratio between quantiles
# FC
r2 <- calc_R2(Data_all=fc_pheno2, response1="PCL_score")
perf1[c("R2","NagelkerkeR2","C-index","OR"),"FC"] <- r2[c("R2","NagelkerkeR2","C-index","OR")]
# FC
r2 <- calc_R2(Data_all=gtp_pheno2, response1="PSStotal")
perf1[c("R2","NagelkerkeR2","C-index","OR"),"GTP"] <- r2[c("R2","NagelkerkeR2","C-index","OR")]
# FC
r2 <- calc_R2(Data_all=aur_pheno2, response1="M3_PCL5_RS")
perf1[c("R2","NagelkerkeR2","C-index","OR"),"AURORA"] <- r2[c("R2","NagelkerkeR2","C-index","OR")]

perf1
```



```{r}
save(AUC3, perf1, file = "/data/humgen/burook/ptsd_multimodal_prediction_stage1/model1_perf.RData")
```




